#!/bin/bash
set -euo pipefail

echo "=== Building Debian Package ==="

# Run build in Docker container
docker run --rm \
    -v "$(pwd):/build" \
    -w /build \
    rust-debtools:latest \
    bash -c '
        set -euo pipefail

        echo "Building for aarch64 (arm64)..."

        # Build the release binary
        cargo build --release --target aarch64-unknown-linux-gnu

        # Get version from Cargo.toml
        VERSION=$(grep "^version" Cargo.toml | head -1 | sed "s/.*\"\(.*\)\"/\1/")
        PACKAGE_NAME="homarr-container-adapter"

        echo "Package: ${PACKAGE_NAME}"
        echo "Version: ${VERSION}"

        # Create package directory structure
        PKG_DIR="${PACKAGE_NAME}_${VERSION}_arm64"
        rm -rf "$PKG_DIR"
        mkdir -p "$PKG_DIR/DEBIAN"
        mkdir -p "$PKG_DIR/usr/bin"
        mkdir -p "$PKG_DIR/lib/systemd/system"
        mkdir -p "$PKG_DIR/etc/homarr-container-adapter"
        mkdir -p "$PKG_DIR/var/lib/homarr-container-adapter"
        mkdir -p "$PKG_DIR/usr/share/lintian/overrides"

        # Copy binary
        cp target/aarch64-unknown-linux-gnu/release/homarr-container-adapter "$PKG_DIR/usr/bin/"
        chmod 755 "$PKG_DIR/usr/bin/homarr-container-adapter"

        # Copy systemd service
        cp debian/homarr-container-adapter.service "$PKG_DIR/lib/systemd/system/"

        # Copy lintian overrides if present
        if [ -f lintian-overrides ]; then
            cp lintian-overrides "$PKG_DIR/usr/share/lintian/overrides/${PACKAGE_NAME}"
        fi

        # Read debian version from changelog (generated by CI)
        if [ -f debian/changelog ]; then
            DEB_VERSION=$(head -1 debian/changelog | sed "s/.*(\(.*\)).*/\1/")
        else
            DEB_VERSION="${VERSION}-1"
        fi

        # Create control file
        cat > "$PKG_DIR/DEBIAN/control" << EOF
Package: ${PACKAGE_NAME}
Version: ${DEB_VERSION}
Architecture: arm64
Maintainer: Matti Airas <matti.airas@hatlabs.fi>
Depends: halos-homarr-branding
Description: Homarr dashboard adapter for HaLOS
 Adapter service that handles first-boot setup and container
 auto-discovery for the Homarr dashboard.
 .
 Features:
  - Completes Homarr onboarding with HaLOS branding
  - Creates admin user and default dashboard
  - Watches Docker events for real-time container discovery
  - Auto-adds containers with homarr.* labels to dashboard
EOF

        # Copy maintainer scripts from debian/
        cp debian/postinst "$PKG_DIR/DEBIAN/postinst"
        chmod 755 "$PKG_DIR/DEBIAN/postinst"

        cp debian/postrm "$PKG_DIR/DEBIAN/postrm"
        chmod 755 "$PKG_DIR/DEBIAN/postrm"

        # Build the package
        dpkg-deb --build "$PKG_DIR"

        # Rename to standard format (only if different)
        SRC_DEB="${PKG_DIR}.deb"
        DST_DEB="${PACKAGE_NAME}_${DEB_VERSION}_arm64.deb"
        if [ "$SRC_DEB" != "$DST_DEB" ]; then
            mv "$SRC_DEB" "$DST_DEB"
        fi

        echo "=== Package built successfully ==="
        ls -la *.deb
    '

# Package is already in workspace root (Docker volume mount)
# Just verify it exists
echo "=== Build complete ==="
ls -la *.deb
