name: 'Check Version Consistency'
description: 'Verify VERSION file matches Cargo.toml version'

runs:
  using: 'composite'
  steps:
    - name: Check version consistency
      shell: bash
      run: |
        set -euo pipefail

        # Read canonical version from VERSION file
        if [ ! -f "VERSION" ]; then
          echo "ERROR: VERSION file not found"
          exit 1
        fi
        VERSION_FILE=$(tr -d '[:space:]' < VERSION)
        if [ -z "$VERSION_FILE" ]; then
          echo "ERROR: VERSION file is empty"
          exit 1
        fi
        echo "VERSION file: $VERSION_FILE"

        # Check Cargo.toml exists
        if [ ! -f "Cargo.toml" ]; then
          echo "ERROR: Cargo.toml not found"
          exit 1
        fi

        # Extract version from Cargo.toml
        CARGO_VERSION=$(grep -m1 '^version = "' Cargo.toml | sed 's/version = "\([^"]*\)".*/\1/' || true)
        if [ -z "$CARGO_VERSION" ]; then
          echo "ERROR: Could not extract version from Cargo.toml"
          exit 1
        fi
        echo "Cargo.toml:   $CARGO_VERSION"

        # Compare
        if [ "$VERSION_FILE" != "$CARGO_VERSION" ]; then
          echo ""
          echo "Version mismatch detected!"
          echo "  VERSION file: $VERSION_FILE"
          echo "  Cargo.toml:   $CARGO_VERSION"
          echo ""
          echo "Use './run bumpversion [patch|minor|major]' to update versions consistently."
          exit 1
        fi

        echo ""
        echo "Version check passed: $VERSION_FILE"
